const path = require('path')
const { StaticPool } = require("node-worker-threads-pool");
const wait = require('./wait')

const waitTime = 100

const staticPool = new StaticPool({
    size: 4,
    task: (param) => {
        console.log(__filename, __dirname) // -> "[worker eval] ."
        this.require('./wait')(param)
        return 'payload generated by worker thread'
    },
});


async function doBlockingWork() {
    return new Promise((resolve) => {

        wait(waitTime)
        resolve('payload generated by blocking work')
    })
}

async function doBlockingWorkWithWorkers() {
    return staticPool.exec(waitTime)
}

exports.doBlockingWork = doBlockingWork
exports.doBlockingWorkWithWorkers = doBlockingWorkWithWorkers
